name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Upewnij się, że to jest gałąź, na którą robisz push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7  # Użyj wersji Ruby, która jest kompatybilna z Twoim projektem

      - name: Install dependencies
        run: |
          cd frontend
          gem install bundler
          bundle install

      - name: Build the Jekyll site
        run: |
          cd frontend
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/_site