name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main  # lub 'master', jeśli to główna gałąź repozytorium

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Możesz zmienić na wersję, której używasz

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build project
        working-directory: frontend
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_PAT }}
          branch: gh-pages
          folder: frontend/dist  # Folder, który ma zostać opublikowany
          clean: true